language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy libhdf5-serial-dev libgdal1-dev libblas-dev liblapack-dev gfortran
install:
  - pip install git+https://github.com/geopython/OWSLib.git
  - pip install -r requirements.txt
script: py.test

